### ISSUE TITLE
Consider units while parsing between styles

### ISSUE THREAD

**Issue by mholthausen** [geostyler/geostyler-style#188]
# Feature Request

**Is your feature request related to a problem? Please describe.**
The units of individual objects must be defined by the initial style and passed on to the GeoStyler style. From there, the defined unit must be sent to the target style.

**Describe the solution you'd like**
GeoStyler should use the units of the source style when converting until other units are defined there. These should then also be applied in the target style.  
See also https://github.com/geostyler/geostyler/discussions/1434

**Additional context**
At the moment, especially in _geostyler-qgis-parser_, the units in the code are hard defined as `Pixel` or missing entirely (e.g. `line_width_unit`)

**Comment by jansule** [comment]
Thanks for opening the issue @mholthausen. Absolutely +1 on that.

I moved this issue to geostyler-style as in the first place this requires the support for units in our style format.

Writing default values in the parsers is a different topic and worth its own issue. So I created a separate issue for that: https://github.com/geostyler/geostyler/issues/1444
