### ISSUE TITLE
Is the LICENSE of the repository BSD-2-Clause?

### ISSUE THREAD

**Issue by allyoucanmap** [geostyler/geostyler-style#490]
# Question

I noticed that the LICENSE file is missing in the repository and the [package.json](https://github.com/geostyler/geostyler-style/blob/v7.1.0/package.json#L38) file defines the `license` as `BSD-2-Clause`.
I'm asking just to make sure that the LICENSE of the repository is still BSD-2-Clause, thanks.

**Comment by jansule** [comment]
Very good point. Thanks @allyoucanmap! Yes, this repo is licensed as `BSD-2-Clause`. I will add a LICENSE file accordingly.

**Comment by jansule** [comment]
Done in https://github.com/geostyler/geostyler-style/pull/491

**Comment by allyoucanmap** [comment]
@jansule thanks
